# version: '3.8'

# services:
#   server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - redis
#     # environment:
#       # - NODE_ENV=production
#     # Add any other configurations needed for your server

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     # Add any other configurations needed for your Redis server

version: '3.8'

services:
  server:
    image: prathibha097/av-bids
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
